Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
srun: error: nid02248: tasks 1-7: Exited with exit code 1
srun: Terminating job step 19395610.0
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
srun: error: nid02250: tasks 16-23: Exited with exit code 1
srun: error: nid02263: tasks 72-79: Exited with exit code 1
srun: error: nid02260: tasks 48-55: Exited with exit code 1
srun: error: nid02262: tasks 64-71: Exited with exit code 1
srun: error: nid02249: tasks 8-15: Exited with exit code 1
srun: error: nid02261: tasks 56-63: Exited with exit code 1
srun: error: nid02257: tasks 32-39: Exited with exit code 1
srun: error: nid02258: tasks 40-47: Exited with exit code 1
srun: error: nid02251: tasks 24-31: Exited with exit code 1
srun: error: nid02248: task 0: Exited with exit code 1
