Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
Traceback (most recent call last):
  File "collect_mpi_part2.py", line 1, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
    from mpi4py import MPI
ImportError: cannot import name MPI
srun: error: nid01525: tasks 16-23: Exited with exit code 1
srun: Terminating job step 19395611.0
srun: error: nid01524: tasks 8-15: Exited with exit code 1
srun: error: nid01526: tasks 24-31: Exited with exit code 1
srun: error: nid01531: tasks 64-71: Exited with exit code 1
srun: error: nid01527: tasks 32-39: Exited with exit code 1
srun: error: nid01529: tasks 48-55: Exited with exit code 1
srun: error: nid01528: tasks 40-47: Exited with exit code 1
srun: error: nid01530: tasks 56-63: Exited with exit code 1
srun: error: nid01532: tasks 72-79: Exited with exit code 1
srun: error: nid01523: tasks 0-7: Exited with exit code 1
